#' Infer K-means Cluster Labels from MOFA latent factors
#'
#' @description
#' Performs k-means clustering on aligned MOFA latent factors
#' generated by \code{s3_plot_query_samples_mofa()}.
#'
#' @details
#' For each sample folder, this function loads either
#' `<sample_id>_stable_input.csv` or
#' `<sample_id>_retrained_LFs_all_samples.csv` (controlled via `input_type`)
#'
#'
#' For each sample, a CSV file is written containing cluster assignments:
#' \itemize{
#'   \item `<sample_id>_sample_clusters.csv` — columns: sample, kmeans_cluster
#' }
#'
#' @name infer_kmeans_clusters
#'
#' @param models_dir      Root directory folder. Same as `s1_add_sample_to_mofa() outdir`.
#'
#' @param k               Integer. Number of k-means clusters.
#'
#' @param input_type Character. Which aligned matrix to use as input.
#'   Either \code{"stable"} (reference-aligned space) or
#'   \code{"retrained"} (retrained latent factors).
#'
#' @param lf_cols Character vector specifying which latent factor columns
#'   (e.g. "Factor1", "Factor2") to use as features for k-means clustering.
#'   These columns must exist in the selected input matrix (controlled via \code{input_type})
#'   and define the feature space used for clustering.
#'
#' @param prefix          Optional character prefix for output files.
#'
#'
#' @return Invisibly returns NULL.
#'
#' @examples
#' mofa_dir <- system.file("extdata/MESOMICS_references", package = "PACMOS")
#' reference_LFs <- system.file(
#'   "extdata/MESOMICS_references",
#'   "MESOMICS_latent_factors.csv",
#'   package = "PACMOS"
#' )
#' query_csv <- system.file(
#'   "extdata/test_data",
#'   "MESOMICS_test_expr.csv",
#'   package = "PACMOS"
#' )
#' out_dir <- file.path(tempdir(), "pacmos_s4")
#' dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
#'
#' s1_add_sample_to_mofa(
#'   query_matrix_path = query_csv,
#'   mofa_dir = mofa_dir,
#'   value_data_types = "D_exprB_MOFA",
#'   outdir = out_dir,
#'   python_bin = Sys.which("/home/lipikal/miniconda3/envs/pacmos_env/bin/python")
#' )
#'
#' s2_run_mofa(
#'   models_dir = out_dir,
#'   matrices_subdir = "inputs",
#'   num_factors = 2,
#'   convergence_mode = "fast",
#'   maxiter = 5,
#'   use_basilisk = FALSE,
#'   skip_existing = TRUE,
#'   python_bin = Sys.which("/home/lipikal/miniconda3/envs/pacmos_env/bin/python"),
#'   views_map = c(RNA = "D_exprB_MOFA"),
#'   binary_views = NULL
#' )
#'
#' sample_id <- basename(list.dirs(out_dir, recursive = FALSE, full.names = TRUE)[1])
#'
#' s3_plot_query_samples_mofa(
#'   models_dir = out_dir,
#'   matrices_subdir = "inputs",
#'   query_sample = sample_id,
#'   reference_LFs = reference_LFs,
#'   reference_axes = c("Morphology_LF", "Adaptive-response_LF"),
#'   group = "group1",
#'   python_bin = Sys.which("/home/lipikal/miniconda3/envs/pacmos_env/bin/python")
#' )
#'
#' infer_kmeans_clusters(
#'   models_dir = out_dir,
#'   k = 3,
#'   input_type = "stable",
#'   lf_cols = c("Morphology_LF", "Adaptive-response_LF")
#' )
#'
#'
#' @export
infer_kmeans_clusters <- function(
    models_dir,
    k,
    input_type = c("stable", "retrained"),
    lf_cols,
    prefix  = ""
    ) {

  # ---- checks --------------------------------------------------------------

  if (!dir.exists(models_dir))
    stop("models_dir does not exist: ", models_dir)

  if (missing(k) || !is.numeric(k) || k < 2)
    stop("k must be an integer >= 2.")

  if (missing(lf_cols) || !is.character(lf_cols) || !length(lf_cols))
    stop("lf_cols must be a non-empty character vector of column names.")

  message("K-means settings - k: ", k,
          " | features: ", paste(lf_cols, collapse = ", "))

  # ---- discover valid sample dirs ------------------------------------------

  input_type <- match.arg(input_type)

  file_suffix <- switch(input_type,
                        stable    = "_stable_input.csv",
                        retrained = "_retrained_LFs_all_samples.csv"
  )

  sample_dirs <- list.dirs(models_dir, recursive = FALSE, full.names = TRUE)

  sample_dirs <- sample_dirs[
    file.exists(
      file.path(sample_dirs, "outputs",
                paste0(basename(sample_dirs), file_suffix))
    )
  ]

  if (!length(sample_dirs))
    stop("No valid sample dirs found. Check models_dir and outputs folder.")

  message("Found ", length(sample_dirs), " sample dir(s).")

  # ---- main loop -----------------------------------------------------------

  for (i in seq_along(sample_dirs)) {

    sdir      <- sample_dirs[i]
    sample_id <- basename(sdir)

    message("")
    message(strrep("=", 45))
    message(sprintf("  [%d / %d]  %s", i, length(sample_dirs), sample_id))
    message(strrep("=", 45))

    si_path <- file.path(
      sdir, "outputs",
      paste0(sample_id, file_suffix)
    )

    input_df <- read.csv(si_path, check.names = FALSE)

    if (!("Sample" %in% colnames(input_df))) {
      stop("Column 'Sample' not found in: ", basename(si_path))
    }

    sid_col <- as.character(input_df[["Sample"]])

    # ---- validate LF columns -----------------------------------------------

    missing_cols <- setdiff(lf_cols, colnames(input_df))
    if (length(missing_cols)) {
      message("  [SKIP] Missing LF columns: ",
              paste(missing_cols, collapse = ", "))
      next
    }

    lf_data <- input_df[, lf_cols, drop = FALSE]
    rownames(lf_data) <- sid_col


    if (ncol(lf_data) == 0) {
      message("  [SKIP] No valid LF columns selected.")
      next
    }

    if (nrow(lf_data) < k) {
      message("  [SKIP] Fewer samples (", nrow(lf_data), ") than k=", k)
      next
    }

    # ---- k-means on ALL samples in selected input ----------------------------

    km <- tryCatch(
      kmeans(lf_data, centers = k, nstart = 25, iter.max = 100),
      error = function(e) {
        message("  [SKIP] kmeans error: ", conditionMessage(e))
        NULL
      }
    )

    if (is.null(km)) next

    # ---- CSV: sample - kmeans_cluster --------------------------------------

    cluster_df <- data.frame(
      sample         = sid_col,
      kmeans_cluster = as.integer(km$cluster),
      stringsAsFactors = FALSE
    )

    csv_out <- file.path(sdir, "outputs",
                         paste0(prefix, sample_id, "_sample_clusters.csv"))
    write.csv(cluster_df, csv_out, row.names = FALSE)
    message("  Saved: ", basename(csv_out))
  }

  message("")
  message(strrep("=", 45))
  message("  Done. Cluster CSVs saved per sample.")
  message(strrep("=", 45))

  invisible(NULL)
}
